describe("Projects", function() {
  var project_window;

  beforeEach(function() {
	projects_json = "[{\"full_name\":\"jesses16/ghgp_test\",\"has_downloads\":true,\"watchers\":1,\"updated_at\":\"2012-06-05T23:26:01Z\",\"homepage\":null,\"url\":\"https://api.github.com/repos/jesses16/ghgp_test\",\"permissions\":{\"pull\":true,\"admin\":false,\"push\":true},\"has_wiki\":true,\"has_issues\":true,\"fork\":false,\"forks\":0,\"svn_url\":\"https://github.com/jesses16/ghgp_test\",\"mirror_url\":null,\"size\":0,\"html_url\":\"https://github.com/jesses16/ghgp_test\",\"private\":true,\"open_issues\":0,\"git_url\":\"git://github.com/jesses16/ghgp_test.git\",\"owner\":{\"url\":\"https://api.github.com/users/jesses16\",\"gravatar_id\":\"82f477aea4fdfcbfed703203a2e1e88e\",\"login\":\"jesses16\",\"avatar_url\":\"https://secure.gravatar.com/avatar/82f477aea4fdfcbfed703203a2e1e88e?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-140.png\",\"id\":365420},\"name\":\"ghgp_test\",\"pushed_at\":\"2012-06-05T23:26:01Z\",\"id\":4566708,\"language\":null,\"description\":\"\",\"clone_url\":\"https://github.com/jesses16/ghgp_test.git\",\"ssh_url\":\"git@github.com:jesses16/ghgp_test.git\",\"created_at\":\"2012-06-05T23:26:01Z\"},{\"full_name\":\"jesses16/Github_GuestPass\",\"has_downloads\":true,\"watchers\":2,\"updated_at\":\"2012-06-05T06:18:47Z\",\"homepage\":null,\"url\":\"https://api.github.com/repos/jesses16/Github_GuestPass\",\"permissions\":{\"pull\":true,\"admin\":false,\"push\":true},\"has_wiki\":true,\"has_issues\":true,\"fork\":false,\"forks\":1,\"svn_url\":\"https://github.com/jesses16/Github_GuestPass\",\"mirror_url\":null,\"size\":180,\"html_url\":\"https://github.com/jesses16/Github_GuestPass\",\"private\":false,\"open_issues\":0,\"git_url\":\"git://github.com/jesses16/Github_GuestPass.git\",\"owner\":{\"url\":\"https://api.github.com/users/jesses16\",\"gravatar_id\":\"82f477aea4fdfcbfed703203a2e1e88e\",\"login\":\"jesses16\",\"avatar_url\":\"https://secure.gravatar.com/avatar/82f477aea4fdfcbfed703203a2e1e88e?d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-140.png\",\"id\":365420},\"name\":\"Github_GuestPass\",\"pushed_at\":\"2012-06-05T06:18:46Z\",\"id\":4402294,\"language\":\"Ruby\",\"description\":\"A system for granting temporary viewer access to a private github repo.\",\"clone_url\":\"https://github.com/jesses16/Github_GuestPass.git\",\"ssh_url\":\"git@github.com:jesses16/Github_GuestPass.git\",\"created_at\":\"2012-05-22T04:38:33Z\"}]"
  });

  it("should fetch the projects for this programmer", function() {
	//pending "Send message to rails server to get projects";
  });
});